services:
  app:
    image: registry.qmweb.fr/${APP_NAME}:latest
    pull_policy: always
    restart: on-failure:2
    ports:
      - 3000
    env_file:
      - ./.env
    command: yarn run start:prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
